### ISSUE TITLE
Plugin doesn't work. Getting "Error: Unable to load code: Error"

### ISSUE THREAD

**Issue by pawelkontek** [wakatime/figma-wakatime#2]
Plugin doesn't work. Getting "Error: Unable to load code: Error".

**Comment by alanhamlett** [comment]
This plugin is a placeholder while we wait for Figma's plugin API to support user events. Until then, it's not possible to build a WakaTime plugin for Figma.

**Comment by alanhamlett** [comment]
Added readme explaining current state of the plugin with 99a538ab5859c1d2ce4efe32d00a7976c03a37f7.
